apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-config
  namespace: finance
data:
  # Eureka
  EUREKA_HOST: "eureka-server"
  EUREKA_USERNAME: "admin"

  # Kafka
  KAFKA_SERVERS: "kafka:9092"

  # Redis
  REDIS_HOST: "redis"

  # Database Hosts
  MYSQL_ACCOUNT_HOST: "mysql-account"
  MYSQL_PAYMENT_HOST: "mysql-payment"
  MYSQL_FRAUD_HOST:   "mysql-fraud"
  MYSQL_LOAN_HOST:    "mysql-loan"
  MYSQL_STOCK_HOST:   "mysql-stock"
  MONGO_HOST:         "mongodb"

  # Database Names
  MYSQL_ACCOUNT_DB: "account_db"
  MYSQL_PAYMENT_DB: "payment_db"
  MYSQL_FRAUD_DB:   "fraud_db"
  MYSQL_LOAN_DB:    "loan_db"
  MYSQL_STOCK_DB:   "stock_db"

  # Mongo
  MONGO_USERNAME: "admin"
